catalog.name=book-catalog
%test.catalog.name=book-catalog-test

quarkus.datasource.devservices.image-name=docker.io/library/postgres:18
quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.devservices.volumes."../volumes/quarkus-demo"=/var/lib/postgresql
quarkus.datasource.devservices.reuse=false

quarkus.hibernate-orm.schema-management.strategy=validate

quarkus.flyway.migrate-at-start=true

quarkus.log.level=INFO
quarkus.log.category."dev.ldv".level=DEBUG
%test.quarkus.log.category."WebApplicationException".level=DEBUG

quarkus.rest.exception-mapping.disable-mapper-for=io.quarkus.resteasy.reactive.jackson.runtime.mappers.BuiltinMismatchedInputExceptionMapper
