CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    author VARCHAR(200) NOT NULL,
    publication_year INTEGER NOT NULL,
    CONSTRAINT publication_year_range CHECK (publication_year BETWEEN 1 AND 2100)
);